language: node_js
node_js:
  - "6"
  - "8"
dist: trusty
sudo: true

before_install:
  # Needed for build-functions.sh (realpath)
  - sudo apt-get install coreutils

install:
  - npm i -g npm@5.6.0 # this should be deleted once 5.7.X is out of "pre-release"
  - npm ci
  # Create file & folder for Travis logs
  - mkdir -p $LOGS_DIR
  - touch $LOGS_DIR/build-perf.log

env:
  global:
    - LOGS_DIR=/tmp/stark/logs
    - LOGS_FILE=/tmp/stark/logs/build-perf.log

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.npm

addons:
  chrome: stable

script:
  - npm run lint:starter
