language: node_js
node_js:
  - "6"
  - "8"
dist: trusty
sudo: true

before_install:
  # Needed for build-functions.sh (realpath)
  - sudo apt-get install realpath

env:
  global:
    - LOGS_DIR=/tmp/stark/logs
    - LOGS_FILE=/tmp/stark/logs/build-perf.log

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.npm

addons:
  chrome: stable

script:
  - npm run lint:starter
