language: node_js
node_js:
  - "6"
  - "8"
dist: trusty
sudo: false

env:
  global:
    - LOGS_DIR=/tmp/stark/logs

branches:
  only:
  - master

cache:
  directories:
    - node_modules
    - packages/stark-build/node_modules
    - packages/stark-core/node_modules

addons:
  chrome: stable

before_script:
  - mkdir -p $LOGS_DIR

script:
  - npm run lint:starter
