version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/packages/stark-build"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "@angular-builders/*"
          version_requirement: "^7.0.0"
      - match:
          dependency_name: "@angular/*"
          version_requirement: "^7.0.0"

  - package_manager: "javascript"
    directory: "/packages/stark-core"
    update_schedule: "live"
    ignored_updates:
     - match:
          dependency_name: "@uirouter/angular"
          version_requirement: "<6.x"      
     - match:
          dependency_name: "@types/node"

  - package_manager: "javascript"
    directory: "/packages/stark-core"
    update_schedule: "live"
    version_requirement_updates: off
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"

  - package_manager: "javascript"
    directory: "/packages/stark-rbac"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "@types/node"

  - package_manager: "javascript"
    directory: "/packages/stark-testing"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "@types/node"

  - package_manager: "javascript"
    directory: "/packages/stark-ui"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "@angular/*"
          version_requirement: "^7.0.0"
      - match:
          dependency_name: "@types/node"

  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "@angular/*"
          version_requirement: "^7.0.0"
      - match:
          dependency_name: "@compodoc/compodoc"
      - match:
          dependency_name: "@types/node"
      - match:
          dependency_name: "typescript"

  - package_manager: "javascript"
    directory: "/showcase"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "@angular/*"
          version_requirement: "^7.0.0"
      - match:
          dependency_name: "@compodoc/compodoc"
      - match:
          dependency_name: "@types/node"
      - match:
          dependency_name: "typescript"

  - package_manager: "javascript"
    directory: "/starter"
    update_schedule: "live"
    ignored_updates:
      - match:
          dependency_name: "@angular/*"
          version_requirement: "^7.0.0"
      - match:
          dependency_name: "@compodoc/compodoc"
      - match:
          dependency_name: "@types/node"
      - match:
          dependency_name: "typescript"
