name: CI

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - master
      - /^\d+\.\d+\.\d(-alpha\.\d+|-beta\.\d+|-rc\.\d+)?$/
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      LOGS_DIR: /tmp/stark/logs
      LOGS_FILE: /tmp/stark/logs/build-perf.log
      TZ: "Europe/Brussels"
      
    strategy:
      matrix:
        node_version: ['10', '12']
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}

      - name: Create file & folder for Travis logs
        run: |
          # cfr scripts/_travis-fold.sh
          mkdir -p $LOGS_DIR
          touch $LOGS_FILE
          
      - name: Get the version 2
        id: get_version2
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: List main variables
        run: |
          echo "Commit SHA  : ${GITHUB_SHA}"
          echo "Reference   : ${GITHUB_REF}"
          echo "Event       : ${GITHUB_EVENT_NAME}"
          echo "Author      : ${GITHUB_ACTOR}"
          HEAD_TAG="$(git tag --points-at HEAD)"
          echo "HEAD_TAG    : ${HEAD_TAG}"
          echo "GH_ACTIONS_TAG    : ${GH_ACTIONS_TAG}"
          echo "GH_ACTIONS_TAG2    : ${GH_ACTIONS_TAG2}"
          NODE_VERSION="$(node -v)"
          echo "Node version: $NODE_VERSION"
          npm i -g npm@6.9.2
          # This ensures that we are authenticated without requiring to have an actual .npmrc file within the project
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
        env:
          GH_ACTIONS_NODE_VERSION: ${{ matrix.node_version }}
          GH_ACTIONS_TAG: ${{ steps.get_version.outputs.VERSION }}
          GH_ACTIONS_TAG2: ${{ steps.get_version2.outputs.VERSION }}

      - name: Run script print-logs
        run: bash ./scripts/ci/print-logs.sh

      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci
          npm run install:ci:all

      - name: "Build showcase:ghpages"
        run: npm run build:showcase:ghpages

      - name: Linting and testing
        run: |
          npm run lint:all
          npm run test:ci:all

      - name: Browserstack testing
        run: |
          #npm run test:showcase:e2e:browserstack
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        if: matrix.node_version == '10' && matrix.os == 'ubuntu-latest'

      - name: Generate and publish docs
        run: |
          #npm run docs:coverage
          #npm run docs:publish
        env:
          encrypted_084795922354_iv: ${{ secrets.encrypted_084795922354_iv }}
          encrypted_084795922354_key: ${{ secrets.encrypted_084795922354_key }}

      - name: Release stark
        run: |
          #npm run release:publish

      - name: Save logs
        run: |
          bash ./scripts/ci/print-logs.sh

      - name: Combine coveralls reports
        run: |
          node combine-packages-coverage.js

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "combined-lcov.info"
        if: github.event_name == 'push'
