name: Dependabot - Sync stark-* packages dependencies versions

on:
  workflow_run:
    workflows: ["Dependabot Pull Request check"]
    types:
      - completed
env:
  TZ: "Europe/Brussels"
  NPM_VERSION: "latest-6"

jobs:
  run_checks:
    runs-on: "ubuntu-latest"
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
      && github.actor == 'dependabot[bot]'
    env:
      PR_NUMBER: "${{ github.event.workflow_run.pull_requests[0].number }}"
    name: "Sync Stark-* dependencies versions for Dependabot PR #${{ github.event.workflow_run.pull_requests[0].number }}"
    steps:
      # See: https://github.com/marketplace/actions/setup-node-js-environment
      - name: Use Node.js 10
        uses: actions/setup-node@v2
        with:
          node-version: 10

      - name: Install npm ${{ env.NPM_VERSION }}
        run: npm i -g npm@${{ env.NPM_VERSION }}

      - name: List main variables
        run: |
          echo "Commit SHA  : ${GITHUB_SHA}"
          echo "Reference   : ${GITHUB_REF}"
          echo "Head branch : ${GITHUB_HEAD_REF}"
          echo "Base branch : ${GITHUB_BASE_REF}"
          echo "Build number: ${GITHUB_RUN_NUMBER}"
          echo "Repository  : ${GITHUB_REPOSITORY}"
          echo "Event       : ${GITHUB_EVENT_NAME}"
          echo "Author      : ${GITHUB_ACTOR}"
          echo "PR Number   : ${PR_NUMBER}"

      # See: https://github.com/marketplace/actions/checkout
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Configure git user info
        run: |
          git config --local user.name "NBB Bot"
          git config --local user.email "83765996+nbb-bot@users.noreply.github.com"

      - name: Sync stark packages dependendencies
        run: |
          echo "Sync packages dependencies when based on Dependabot update for PR ${PR_NUMBER}: $(_jq '.title')"
          npm run sync:packages-dependencies
          git push

          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.BOT_TOKEN }}" \
            --data '{"body": "Dependency has been updated in stark-* packages dependencies. You should wait for green result before merging this! :+1:"}' \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments"
