name: Dummy hook

on:
  pull_request_target
  
jobs:
  dummy:
    name: dummy
    runs-on: ubuntu-latest
    steps:
      - name: Show vars
        run: |
          echo ${GITHUB_REF}
          echo ${GITHUB_HEAD_REF}
          echo ${GITHUB_BASE_REF}
          echo GitHub token: ${{ secrets.GITHUB_TOKEN }}
          echo Bot token: ${{ secrets.BOT_TOKEN }}
          echo wrong token: ${{ secrets.BOTI_TOKEN }} 
      
      
